# Generated by Django 5.1.5 on 2025-05-05 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telegram_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Mijoz ismi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('route', models.CharField(max_length=100, verbose_name='Yo‘nalish')),
                ('passport_file', models.FileField(upload_to='passports/', verbose_name='Passport skaneri')),
                ('photo_3x4', models.ImageField(upload_to='photos/', verbose_name='3x4 rasm')),
                ('payment_receipt', models.FileField(upload_to='receipts/', verbose_name='To‘lov cheki')),
                ('status', models.CharField(default='Yangi', max_length=20, verbose_name='Holat')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.agent')),
            ],
        ),
    ]
