# Generated by Django 5.1.5 on 2025-05-05 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=100, verbose_name='Yo‘nalish')),
                ('date', models.DateField(verbose_name='Reys sanasi')),
                ('max_seats', models.PositiveIntegerField(verbose_name='Maksimal o‘rinlar')),
                ('image', models.ImageField(blank=True, upload_to='tours/', verbose_name='Yo‘nalish rasmi')),
                ('note', models.TextField(blank=True, verbose_name='Qo‘shimcha ma’lumot')),
                ('commission_per_client', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Agent komissiyasi (USD)')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='agent_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Komissiya (USD)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.tourschedule'),
            preserve_default=False,
        ),
    ]
