# Generated by Django 5.2 on 2025-05-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_agent_user_alter_agent_name_alter_agent_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('viewed', 'Ko‘rib chiqildi'), ('approved', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='new', max_length=20, verbose_name='Holat'),
        ),
    ]
