# Generated by Django 5.2 on 2025-05-09 18:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='agent_commission',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='passport_file',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_receipt',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='photo_3x4',
        ),
        migrations.RemoveField(
            model_name='tourschedule',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tourschedule',
            name='note',
        ),
        migrations.AddField(
            model_name='booking',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='passports',
            field=models.FileField(blank=True, null=True, upload_to='passports/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='photos',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='receipts',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.agent'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='route',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Yangi', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.tourschedule'),
        ),
        migrations.AlterField(
            model_name='tourschedule',
            name='commission_per_client',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tourschedule',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tourschedule',
            name='direction',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tourschedule',
            name='max_seats',
            field=models.IntegerField(default=0),
        ),
    ]
