# Generated by Django 5.2 on 2025-05-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_agent_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourschedule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/tours/'),
        ),
    ]
