# Generated by Django 5.2 on 2025-05-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_tourschedule_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourschedule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
