# Generated by Django 5.2 on 2025-05-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_tourschedule_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourschedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
