# Generated by Django 5.2 on 2025-05-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_tourschedule_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-id']},
        ),
    ]
