# Generated by Django 5.2 on 2025-05-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('viewed', 'Ko‘rib chiqildi'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='Yangi', max_length=50),
        ),
    ]
